/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CmsProject2C;

import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Test
 */
public class SignUpStudent extends javax.swing.JFrame {

    /**
     * Creates new form signupteacher
     */
    public SignUpStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        sname = new javax.swing.JTextField();
        semail = new javax.swing.JTextField();
        spnumber = new javax.swing.JTextField();
        sfname = new javax.swing.JTextField();
        sid = new javax.swing.JTextField();
        spassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lable1 = new javax.swing.JLabel();
        lable2 = new javax.swing.JLabel();
        lable3 = new javax.swing.JLabel();
        lable4 = new javax.swing.JLabel();
        lable5 = new javax.swing.JLabel();
        lable6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();
        images = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snameActionPerformed(evt);
            }
        });
        sname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                snameKeyReleased(evt);
            }
        });
        jPanel1.add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 103, 180, 35));

        semail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        semail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semailActionPerformed(evt);
            }
        });
        semail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                semailKeyReleased(evt);
            }
        });
        jPanel1.add(semail, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 178, 366, 35));

        spnumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spnumberActionPerformed(evt);
            }
        });
        spnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spnumberKeyReleased(evt);
            }
        });
        jPanel1.add(spnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 257, 180, 35));

        sfname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfnameActionPerformed(evt);
            }
        });
        sfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sfnameKeyReleased(evt);
            }
        });
        jPanel1.add(sfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 103, 180, 35));

        sid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidActionPerformed(evt);
            }
        });
        sid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sidKeyReleased(evt);
            }
        });
        jPanel1.add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 257, 180, 35));

        spassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spasswordActionPerformed(evt);
            }
        });
        spassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spasswordKeyReleased(evt);
            }
        });
        jPanel1.add(spassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 412, 180, 35));

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SignUp");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 60, 28));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Student Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 83, 180, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Father Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 83, 180, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 158, 180, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Student ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 237, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Date Of Birth");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 317, 180, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 392, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Phone Number");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 237, -1, -1));

        lable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lable1.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 140, 180, -1));

        lable2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lable2.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 140, 180, -1));

        lable3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lable3.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 219, 180, -1));

        lable4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lable4.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 294, 180, -1));

        lable5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lable5.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lable5, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 294, 180, -1));

        lable6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lable6.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lable6, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 453, 180, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Use at least 8 character & use  ");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel9.setInheritsPopupMenu(false);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 453, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("only numbers");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 473, -1, 11));

        next.setBackground(new java.awt.Color(255, 51, 0));
        next.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("Back");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, -1, -1));

        date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 342, 366, 40));
        jPanel1.add(images, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 100, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void snameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snameActionPerformed

    private void semailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semailActionPerformed

    private void spnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spnumberActionPerformed

    private void sfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sfnameActionPerformed

    private void sidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidActionPerformed

    private void spasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DB_Model db=new DB_Model();
        DateFormat da = new SimpleDateFormat("YYYY-MM-dd");
         String Date=da.format(date.getDate());
         if(db.ssignup(sname.getText(), sfname.getText(), semail.getText(),sid.getText(),spnumber.getText(),Date,Integer.parseInt(spassword.getText()))==1)
        {
            LoginStudent lg=new LoginStudent();
            lg.setVisible(true);
            dispose();
        }else
        {
            JOptionPane.showMessageDialog(this,"Invalid Data","ALERT",2);
        }
      
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void snameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snameKeyReleased
        // TODO add your handling code here:
        String ui="^[a-zA-Z]{1,}$";
        Pattern usid=Pattern.compile(ui);
        Matcher uid=usid.matcher(sname.getText());
        if(uid.find())
        {
            lable1.setText("");
        }
        else
        {
            lable1.setText("Wrong Input");
        }
    }//GEN-LAST:event_snameKeyReleased

    private void sfnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sfnameKeyReleased
        // TODO add your handling code here:
        String fn="^[a-zA-Z]{1,}$";
        Pattern fnam=Pattern.compile(fn);
        Matcher fname=fnam.matcher(sfname.getText());
        if(fname.find())
        {
            lable2.setText("");
        }
        else
        {
            lable2.setText("Wrong Input");
        }
    }//GEN-LAST:event_sfnameKeyReleased

    private void semailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_semailKeyReleased
        // TODO add your handling code here:
        String gm="^[a-zA-Z0-9@.]{1,}$";
        Pattern mail=Pattern.compile(gm);
        Matcher gmail=mail.matcher(semail.getText());
        if(gmail.find())
        {
            lable3.setText("");
        }
        else
        {
            lable3.setText("Wrong Input");
        }
    }//GEN-LAST:event_semailKeyReleased

    private void sidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sidKeyReleased
        // TODO add your handling code here:
        String tui="^[a-zA-Z0-9-]{1,}$";
        Pattern tusid=Pattern.compile(tui);
        Matcher tuid=tusid.matcher(sid.getText());
        if(tuid.find())
        {
            lable4.setText("");
        }
        else
        {
            lable4.setText("Wrong Input");
        }
    }//GEN-LAST:event_sidKeyReleased

    private void spnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnumberKeyReleased
        // TODO add your handling code here:
        String nui="^[0-9]{1,11}$";
        Pattern nusid=Pattern.compile(nui);
        Matcher nuid=nusid.matcher(spnumber.getText());
        if(nuid.find())
        {
            lable5.setText("");
        }
        else
        {
            lable5.setText("Wrong Input");
        }
    }//GEN-LAST:event_spnumberKeyReleased

    private void spasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spasswordKeyReleased
        // TODO add your handling code here:
        String pui="^[0-9]{1,8}$";
        Pattern pusid=Pattern.compile(pui);
        Matcher puid=pusid.matcher(spassword.getText());
        if(puid.find())
        {
            lable6.setText("");
        }
        else
        {
            lable6.setText("Wrong Input");
        }
    }//GEN-LAST:event_spasswordKeyReleased

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        Homepage select =new Homepage();
        select.setVisible(true);
        dispose();
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel images;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lable1;
    private javax.swing.JLabel lable2;
    private javax.swing.JLabel lable3;
    private javax.swing.JLabel lable4;
    private javax.swing.JLabel lable5;
    private javax.swing.JLabel lable6;
    private javax.swing.JButton next;
    private javax.swing.JTextField semail;
    private javax.swing.JTextField sfname;
    private javax.swing.JTextField sid;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField spassword;
    private javax.swing.JTextField spnumber;
    // End of variables declaration//GEN-END:variables
}
