/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CmsProject2C;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Test
 */
public class SignUpTeacher extends javax.swing.JFrame {

    /**
     * Creates new form signupteacher
     */
    public SignUpTeacher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tname = new javax.swing.JTextField();
        temail = new javax.swing.JTextField();
        tpn = new javax.swing.JTextField();
        tfname = new javax.swing.JTextField();
        tid = new javax.swing.JTextField();
        tpassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lable1 = new javax.swing.JLabel();
        lable2 = new javax.swing.JLabel();
        lable3 = new javax.swing.JLabel();
        lable4 = new javax.swing.JLabel();
        lable5 = new javax.swing.JLabel();
        lable6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tcourse = new javax.swing.JComboBox<>();
        tdepartment = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnameActionPerformed(evt);
            }
        });
        tname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tnameKeyReleased(evt);
            }
        });
        jPanel1.add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 109, 180, 35));

        temail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        temail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temailActionPerformed(evt);
            }
        });
        temail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                temailKeyReleased(evt);
            }
        });
        jPanel1.add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 184, 366, 35));

        tpn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpnActionPerformed(evt);
            }
        });
        tpn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tpnKeyReleased(evt);
            }
        });
        jPanel1.add(tpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 263, 180, 35));

        tfname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameActionPerformed(evt);
            }
        });
        tfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfnameKeyReleased(evt);
            }
        });
        jPanel1.add(tfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 109, 180, 35));

        tid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidActionPerformed(evt);
            }
        });
        tid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tidKeyReleased(evt);
            }
        });
        jPanel1.add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 263, 180, 35));

        tpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpasswordActionPerformed(evt);
            }
        });
        tpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tpasswordKeyReleased(evt);
            }
        });
        jPanel1.add(tpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 452, 180, 35));

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SignUp");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 547, 52, 28));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Teacher Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 89, 180, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Father Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 89, 180, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 164, 180, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Teacher ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 243, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Date Of Birth");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 180, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 432, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Phone Number");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 243, -1, -1));

        lable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lable1.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 146, 180, -1));

        lable2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lable2.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 146, 180, -1));

        lable3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lable3.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 225, 180, -1));

        lable4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lable4.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 300, 180, -1));

        lable5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lable5.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lable5, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 300, 180, -1));

        lable6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lable6.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lable6, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 524, 180, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Use at least 8 character & use  ");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel9.setInheritsPopupMenu(false);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 493, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("only numbers");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 513, -1, 11));

        tcourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course Code:", "CEN-101", "MAT-103", "CHE-456", "PHY-459", "ARB-567" }));
        tcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcourseActionPerformed(evt);
            }
        });
        jPanel1.add(tcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 394, 181, -1));

        tdepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "CS" }));
        tdepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdepartmentActionPerformed(evt);
            }
        });
        jPanel1.add(tdepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 394, 162, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 415, 180, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Department");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 374, 180, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Course Code");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 374, 180, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CmsProject2C/imagesdirection.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 581, -1, 31));

        next.setBackground(new java.awt.Color(255, 51, 0));
        next.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("Back");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 581, -1, -1));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 364, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tdepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdepartmentActionPerformed

    private void tcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcourseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DB_Model db=new DB_Model();
         DateFormat da = new SimpleDateFormat("YYYY-MM-dd");
         String Date=da.format(date.getDate());
       if(db.tsignup(tname.getText(),tfname.getText(),temail.getText(),tid.getText(),tpn.getText(),
               Date,tdepartment.getSelectedItem().toString(),tcourse.getSelectedItem().toString(),Integer.parseInt(tpassword.getText()))==1)
        {
        LoginTeacher myobj=new LoginTeacher();
        myobj.setVisible(true);
        dispose();  
        }else
        {
            JOptionPane.showMessageDialog(this,"Invalid Data","ALERT",2);
        }
      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpasswordKeyReleased
        // TODO add your handling code here:
        String pui="^[0-9]{1,8}$";
        Pattern pusid=Pattern.compile(pui);
        Matcher puid=pusid.matcher(tpassword.getText());
        if(puid.find())
        {
            lable6.setText("");
        }
        else
        {
            lable6.setText("Wrong Input");
        }
    }//GEN-LAST:event_tpasswordKeyReleased

    private void tpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpasswordActionPerformed

    private void tidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tidKeyReleased
        // TODO add your handling code here:
        String tui="^[a-zA-Z0-9-]{1,}$";
        Pattern tusid=Pattern.compile(tui);
        Matcher tuid=tusid.matcher(tid.getText());
        if(tuid.find())
        {
            lable4.setText("");
        }
        else
        {
            lable4.setText("Wrong Input");
        }
    }//GEN-LAST:event_tidKeyReleased

    private void tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidActionPerformed

    private void tfnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnameKeyReleased
        // TODO add your handling code here:
        String fn="^[a-zA-Z]{1,}$";
        Pattern fnam=Pattern.compile(fn);
        Matcher fname=fnam.matcher(tfname.getText());
        if(fname.find())
        {
            lable2.setText("");
        }
        else
        {
            lable2.setText("Wrong Input");
        }
    }//GEN-LAST:event_tfnameKeyReleased

    private void tfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameActionPerformed

    private void tpnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpnKeyReleased
        // TODO add your handling code here:
        String nui="^[0-9]{1,11}$";
        Pattern nusid=Pattern.compile(nui);
        Matcher nuid=nusid.matcher(tpn.getText());
        if(nuid.find())
        {
            lable5.setText("");
        }
        else
        {
            lable5.setText("Wrong Input");
        }
    }//GEN-LAST:event_tpnKeyReleased

    private void tpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpnActionPerformed

    private void temailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_temailKeyReleased
        // TODO add your handling code here:
        String gm="^[a-zA-Z0-9@.]{1,}$";
        Pattern mail=Pattern.compile(gm);
        Matcher gmail=mail.matcher(temail.getText());
        if(gmail.find())
        {
            lable3.setText("");
        }
        else
        {
            lable3.setText("Wrong Input");
        }
    }//GEN-LAST:event_temailKeyReleased

    private void temailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temailActionPerformed

    private void tnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnameKeyReleased
        // TODO add your handling code here:
        String ui="^[a-zA-Z]{1,}$";
        Pattern usid=Pattern.compile(ui);
        Matcher uid=usid.matcher(tname.getText());
        if(uid.find())
        {
            lable1.setText("");
        }
        else
        {
            lable1.setText("Wrong Input");
        }
    }//GEN-LAST:event_tnameKeyReleased

    private void tnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnameActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        Homepage select =new Homepage();
        select.setVisible(true);
        dispose();
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lable1;
    private javax.swing.JLabel lable2;
    private javax.swing.JLabel lable3;
    private javax.swing.JLabel lable4;
    private javax.swing.JLabel lable5;
    private javax.swing.JLabel lable6;
    private javax.swing.JButton next;
    private javax.swing.JComboBox<String> tcourse;
    private javax.swing.JComboBox<String> tdepartment;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tpassword;
    private javax.swing.JTextField tpn;
    // End of variables declaration//GEN-END:variables
}
