/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CmsProject2C;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author laptop city
 */
public class StudentCourseRegister extends javax.swing.JFrame {
    ResultSet rs;
    /**
     * Creates new form TeacherProfile
     */
    public StudentCourseRegister(String sname,String Id) {
        initComponents();
        name.setText(sname);
        ID.setText(Id);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        instructor = new javax.swing.JComboBox<>();
        subject = new javax.swing.JComboBox<>();
        career = new javax.swing.JComboBox<>();
        select_course = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        ID = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Course Select:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 238, 222, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Course Subject:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 100, 222, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Course Career:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 169, 222, -1));

        instructor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        instructor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Ameen Khawaja", "Irfan Ali", "Umair Rais", "DR.Haque", "DR.Naila", " " }));
        jPanel1.add(instructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 323, 222, 30));

        subject.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Computer Science" }));
        jPanel1.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 121, 222, 30));

        career.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        career.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Undergraduate", "Graduate" }));
        jPanel1.add(career, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 190, 222, 30));

        select_course.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        select_course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course Code", "CEN-101", "MAT-103", "CHE-456", "PHY-459", "ARB-567" }));
        jPanel1.add(select_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 259, 222, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Course Instructor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 302, 222, -1));

        name.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 166, 25));

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 392, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CmsProject2C/imagesdirection.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        next.setBackground(new java.awt.Color(255, 51, 0));
        next.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("Back");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));

        ID.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 166, 25));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CmsProject2C/images/namepic.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CmsProject2C/images/id images.jpg"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 30, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DB_Model db=new DB_Model();
        //String cfind=null;
        int s=0;
        rs=db.coursefind(select_course.getSelectedItem().toString(),ID.getText());
        try {
            if(rs.next()){
                s=1;
                System.out.println("Coursecode matched");
                JOptionPane.showMessageDialog(this, "course has not been added","Alert",1);
                }
                if(s==0){
                     if(db.studentregistration(name.getText(), ID.getText(), subject.getSelectedItem().toString(), career.getSelectedItem().toString()
                        ,select_course.getSelectedItem().toString(), instructor.getSelectedItem().toString())==1){
                    
                    JOptionPane.showMessageDialog(this, "course Inserted","Alert",1);
                     }}
                
        } catch (SQLException ex) {
            Logger.getLogger(StudentCourseRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
                 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        StudentDetails sd = new StudentDetails(name.getText(),ID.getText());
        sd.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentCourseRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentCourseRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentCourseRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentCourseRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentCourseRegister("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JComboBox<String> career;
    private javax.swing.JComboBox<String> instructor;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JButton next;
    private javax.swing.JComboBox<String> select_course;
    private javax.swing.JComboBox<String> subject;
    // End of variables declaration//GEN-END:variables
}
