/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CmsProject2C;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laptop city
 */
public class StudentResult extends javax.swing.JFrame {
    ResultSet rs;
    String C_code=null;
    String tname=null;

    /**
     * Creates new form TeacherProfile
     */
    public StudentResult(String tname, String tcourse) {
        this.C_code=tcourse;
        this.tname=tname;
        initComponents();
        DB_Model db=new DB_Model();
        rs=db. studentattendance(tcourse);
        DefaultTableModel tb=(DefaultTableModel)table.getModel();
        try{
        while(rs.next())
        {
            String data[]={rs.getString("S_Name"),rs.getString("S_ID"),rs.getString("Subect"),rs.getString("Career"),rs.getString("Select_Course"),};
            
            tb.addRow(data);
        }
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userid3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        assignment = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        project = new javax.swing.JTextField();
        finalterm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        next = new javax.swing.JButton();
        sname = new javax.swing.JTextField();
        quiz2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Student ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        userid3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        userid3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userid3ActionPerformed(evt);
            }
        });
        userid3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userid3KeyReleased(evt);
            }
        });
        jPanel2.add(userid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Student Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Quiz");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        sid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidActionPerformed(evt);
            }
        });
        sid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sidKeyReleased(evt);
            }
        });
        jPanel2.add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 190, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Assignment");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        assignment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        assignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentActionPerformed(evt);
            }
        });
        assignment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                assignmentKeyReleased(evt);
            }
        });
        jPanel2.add(assignment, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 190, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Mid Term");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        mid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midActionPerformed(evt);
            }
        });
        mid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                midKeyReleased(evt);
            }
        });
        jPanel2.add(mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 190, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Project");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        project.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        project.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectActionPerformed(evt);
            }
        });
        project.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                projectKeyReleased(evt);
            }
        });
        jPanel2.add(project, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 190, 30));

        finalterm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        finalterm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finaltermActionPerformed(evt);
            }
        });
        finalterm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                finaltermKeyReleased(evt);
            }
        });
        jPanel2.add(finalterm, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 190, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Final Term");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Click");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 560, 90, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Student ID", "Course Subject", "Course Career", "Course Select"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 940, 470));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Upload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, -1, -1));

        next.setBackground(new java.awt.Color(255, 51, 0));
        next.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("Back");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel2.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 80, 30));

        sname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snameActionPerformed(evt);
            }
        });
        sname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                snameKeyReleased(evt);
            }
        });
        jPanel2.add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 190, 30));

        quiz2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        quiz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quiz2ActionPerformed(evt);
            }
        });
        quiz2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quiz2KeyReleased(evt);
            }
        });
        jPanel2.add(quiz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1284, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userid3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userid3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userid3ActionPerformed

    private void userid3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userid3KeyReleased
        // TODO add your handling code here:
  
    }//GEN-LAST:event_userid3KeyReleased

    private void sidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidActionPerformed

    private void sidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sidKeyReleased

    private void assignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignmentActionPerformed

    private void assignmentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_assignmentKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_assignmentKeyReleased

    private void midActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midActionPerformed

    private void midKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_midKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_midKeyReleased

    private void projectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectActionPerformed

    private void projectKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_projectKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_projectKeyReleased

    private void finaltermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finaltermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finaltermActionPerformed

    private void finaltermKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_finaltermKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_finaltermKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
         
         DefaultTableModel tb=(DefaultTableModel)table.getModel();
        
         String rowid=(String) tb.getValueAt(table.getSelectedRow(),1);
         String rowname=(String) tb.getValueAt(table.getSelectedRow(),0);
          String coursecode=(String) tb.getValueAt(table.getSelectedRow(),4);
          this.C_code=coursecode;
         
         //DB_Model db=new DB_Model();
         System.out.println(rowid);
         sid.setText(rowid);
         sname.setText(rowname);
     

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DB_Model db = new DB_Model();
        /*if(db.Studentgrades(sid.getText(), sname.getText(), C_code, quiz.getText(),assignment.getText(),mid.getText(),project.getText(),finalterm.getText())==1){
        
           
         JOptionPane.showMessageDialog(this,"Record is Inserted","ALERT",2);
        }else
        {
            JOptionPane.showMessageDialog(this,"Record is not Inserted","ALERT",2);
        }*/
           int s=0;
        rs=db.getStudentGrade(C_code);
        try {
            if(rs.next()){
                s=1;
                System.out.println("Coursecode matched");
                JOptionPane.showMessageDialog(this, "Result already Update","Alert",1);
                }
                if(s==0){
                     if(db.Studentgrades(sid.getText(), sname.getText(), C_code, quiz2.getText(),
                             assignment.getText(),mid.getText(),project.getText(),finalterm.getText())==1){
                    
                    JOptionPane.showMessageDialog(this, "Updated Result ","Alert",1);
                     }}
                else{
                   // JOptionPane.showMessageDialog(this, "Not Updated","Alert",1);
                }
                
        } catch (SQLException ex) {
            Logger.getLogger(StudentCourseRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        TeacherDetails obj = new TeacherDetails(tname,C_code);
        obj.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_nextActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void snameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snameActionPerformed

    private void snameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_snameKeyReleased

    private void quiz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quiz2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quiz2ActionPerformed

    private void quiz2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quiz2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_quiz2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentResult("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assignment;
    private javax.swing.JTextField finalterm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mid;
    private javax.swing.JButton next;
    private javax.swing.JTextField project;
    private javax.swing.JTextField quiz2;
    private javax.swing.JTextField sid;
    private javax.swing.JTextField sname;
    private javax.swing.JTable table;
    private javax.swing.JTextField userid3;
    // End of variables declaration//GEN-END:variables
}
